<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default2.aspx.cs" Inherits="Default2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" class="gv" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="False" AutoGenerateEditButton="True" DataKeyNames="ExpenditureID" DataSourceID="SqlDataSource1" Font-Names="sans-serif">
        <Columns>
            <asp:TemplateField>
                <ItemTemplate>
                    <asp:LinkButton ID="LinkButton1" runat="server" type="button" OnClientClick="return confirm('Are you sure?');" CommandName="Delete">Delete</asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="ExpenditureID" HeaderText="Expenditure ID" InsertVisible="False" ReadOnly="True" SortExpression="ExpenditureID" />
            <asp:BoundField DataField="userid" HeaderText="User ID" SortExpression="userid" ReadOnly="true" />
            <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" ReadOnly="true" />
            <asp:BoundField DataField="amount" HeaderText="Amount" SortExpression="amount" />
            <asp:BoundField DataField="doe" HeaderText="Date" SortExpression="doe" />
            <asp:BoundField DataField="description" HeaderText="Description" SortExpression="description" />
        </Columns>
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:EyugaaDBConnectionString %>" SelectCommand="SELECT * FROM [expenditure]" UpdateCommand="UPDATE expenditure SET amount=@amount, doe=@doe, description=@description WHERE ExpenditureID=@ExpenditureID" DeleteCommand="delete from expenditure where ExpenditureID=@ExpenditureID">
    <UpdateParameters>
        <asp:Parameter Name="amount" Type="String" />
        <asp:Parameter Name="doe" Type="DateTime"/>
        <asp:Parameter Name="description" type="String"/>
    </UpdateParameters>
    <DeleteParameters>
        <asp:Parameter Name="ExpenditureID" />
    </DeleteParameters>
</asp:SqlDataSource>
</asp:Content>

